### ISSUE TITLE
Question about backward process for mask

### ISSUE THREAD

**Issue by JunyuanDeng** [fudan-zvg/4d-gaussian-splatting#23]
Hello, thanks for your great effor.

I have a question about the backward process for mask [here](https://github.com/fudan-zvg/4d-gaussian-splatting/blob/896189e0363ec691a23cb6ddbd67372353c73d1c/diff-gaussian-rasterization/cuda_rasterizer/backward.cu#L1043). It seems that the mask is back propagate as the volume rendering process like depth or color. However, the mask, which is 1-T, is just the multiplication from (1-alpha_1) to (1-alpha_n).

So, in my view, the gradients from masks is just `dL_dalpha += (dL_dmask[pix_id]) * (T_final/(1.f - alpha))` because  `d_mask_d_T = -1, dT_d_alpha = (-T_final / (1.f - alpha))`.

Is this a correct thought?

Thanks for your future reply in advance!

**Comment by Alexander0Yang** [comment]
Hi, @JunyuanDeng, thanks for your interest.

 > Is this a correct thought?

Yes, you‘ve got the right idea.

But please note that 
```math
1 - \prod_{1}^{n} (1-\alpha_{i}) = 1 - T = \sum_{i}^{n} \alpha_{i} \prod^{i-1}_{j} (1-\alpha_{j})
```
They are two equivalent views. Since we used the latter in the forward computation, we kept the same volume-rendering style when compute its gradient in the back-propagation.
Actually, your formulation of gradient is also equal to the current implemention. Because the `(1.0 - accum_mask_rec)` in [L1044](https://github.com/fudan-zvg/4d-gaussian-splatting/blob/main/diff-gaussian-rasterization/cuda_rasterizer/backward.cu#L1044) is the product from (1-alpha_{i+1}) to (1-alpha_{n}) and T in [L1046](https://github.com/fudan-zvg/4d-gaussian-splatting/blob/main/diff-gaussian-rasterization/cuda_rasterizer/backward.cu#L1046) is the product from (1-alpha_{1}) to (1-alpha_{i-1}), so the product of them is just `(T_final/(1.f - alpha_i))`.

**Comment by JunyuanDeng** [comment]
Thanks for your rely, I understood.
