### ISSUE TITLE
Overfitting on dynerf dataset

### ISSUE THREAD

**Issue by RuijieZhu94** [fudan-zvg/4d-gaussian-splatting#36]
Hi, @Alexander0Yang. Thanks for open sourcing this great work.

I followed the instructions in the readme to train the model, but found that it would overfit on the dynerf dataset.
This is the output I get from tensorboard. Can you help me figure out what's going wrong?

![image](https://github.com/fudan-zvg/4d-gaussian-splatting/assets/63986279/0e82de61-e2bf-43e3-a531-5b39087eaeac)

**Comment by zhanglk9** [comment]
I am a newbie. I want to know how to organize N3V dataset.

**Comment by zhanglk9** [comment]
I am a newbie. I want to know how to organize N3V dataset. Can you tell me?

**Comment by Alexander0Yang** [comment]
Hi @RuijieZhu94.
According to our observation, the performance drop in some scenes is caused by the floater obstructing the test camera instead of (the most typical form of) overfitting. For the convenience of reproduction, we report the highest PSNR during training rather than measuring on the final checkpoint with manually floater removing.

**Comment by RuijieZhu94** [comment]
Thank you for your patient answer.
