### ISSUE TITLE
I have some problems with the implementation of backward code

### ISSUE THREAD

**Issue by Ma1hn** [fudan-zvg/4d-gaussian-splatting#48]
I noticed that the backward part using xyz directly from mean4D. But in my opinion, in forward flow, the conditional xyz,  which is inferenced from xyz(from mean4D) by eq(9) in your paper , is used in later work(projection, calculate depth). So I am doubt why don't use condional xyz in backward flow.

**Comment by Alexander0Yang** [comment]
Hi, @Ma1hn,
Great observation! The information required for calculating the gradient from depth is already written in geomState during forward process, so it's not related to the 3D means. However, the updated 3D means should indeed be involved in computation of the gradient of the 3D means from the 2D means. I ignored it as I stopped debug until I found the current version was already enough to reproduce the performance of the python version, and the gradients were also very close to those in the python version. This might be because the gradient of the 3D means is mainly dominated by other parts, and the difference between the 3D means at different time is relatively small.  I’ve fixed it in the latest commit. Thanks for your reminder!
